version: "3.4"
services:
  backend:
    ports:
      - "3031:3031"
      - "9191:9191"
    healthcheck:
      start_period: "5s"
      timeout: "5s"
      interval: "30s"
      retries: 1
      test: "curl frontend/api/online/ -sSf || exit 1"

  prometheus:
    image: prom/prometheus:v2.21.0
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - ./prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana-storage:/var/lib/grafana
    ports:
      - 9091:3000
    depends_on:
      - prometheus
